language: node_js
node_js:
    - "8"
script:
    - npm install
cache:
    directories:
        - "node_modules"
deploy:
    provider: npm
    email: $EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
        tags: true
before_deploy: "npm run build"